name: motion_hackathon_group7_hazelnut
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.3.2 <4.0.0"

# -------------------- PACKAGES -------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1

  # Icons
  iconsax: ^0.0.8
  fluentui_system_icons: ^1.0.0

  # State Management
  get: ^4.6.6
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0

  # -------------------- PACKAGES END -------------------- #

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # -------------------- LOCAL ASSETS -------------------- #
  assets:
    - assets/images/
    - assets/logos/
