name: motion_hackathon_group7_hazelnut
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.3.2 <4.0.0"

# -------------------- PACKAGES -------------------- #
dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  dots_indicator: ^3.0.0
  fluentui_system_icons: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # -------------------- LOCAL ASSETS -------------------- #
  assets:
    - assets/images/
    - assets/logos/
